### ISSUE TITLE
pypy/Twisted incompatibility

### ISSUE THREAD

**Issue by arnimarj** [ionelmc/python-tblib#30]
Hi,

I tried running a few of our internal tests using the latest `pypy` (version 5.10), and hit a compatibility issue with the Twisted Failure object():

```
from tblib import pickling_support
pickling_support.install()

import six, pickle, sys
from twisted.python.failure import Failure

try:
	raise ValueError
except ValueError:
	s = pickle.dumps(sys.exc_info())

try:
	six.reraise(*pickle.loads(s))
except ValueError:
	f = Failure()

print('F', f)
```

This works on both Python 2.7.13, 3.6.3, but not the latest pypy. The error output was:

```
Traceback (most recent call last):
  File "twisted_six.py", line 10, in <module>
    s = pickle.dumps(sys.exc_info())
  File "/home/arni/dohop/pypy-5.10.0-linux_x86_64-portable/lib-python/2.7/pickle.py", line 1431, in dumps
    Pickler(file, protocol).dump(obj)
  File "/home/arni/dohop/pypy-5.10.0-linux_x86_64-portable/lib-python/2.7/pickle.py", line 224, in dump
    self.save(obj)
  File "/home/arni/dohop/pypy-5.10.0-linux_x86_64-portable/lib-python/2.7/pickle.py", line 286, in save
    f(self, obj) # Call unbound method with explicit self
  File "/home/arni/dohop/pypy-5.10.0-linux_x86_64-portable/lib-python/2.7/pickle.py", line 570, in save_tuple
    save(element)
  File "/home/arni/dohop/pypy-5.10.0-linux_x86_64-portable/lib-python/2.7/pickle.py", line 292, in save
    rv = reduce(obj)
  File "/home/arni/dohop/virtualenvs/pypy_5_10/site-packages/tblib/pickling_support.py", line 20, in pickle_traceback
    return unpickle_traceback, (Frame(tb.tb_frame), tb.tb_lineno, tb.tb_next and Traceback(tb.tb_next))
  File "/home/arni/dohop/virtualenvs/pypy_5_10/site-packages/tblib/__init__.py", line 54, in __init__
    self.f_back = Traceback(frame.f_back)
  File "/home/arni/dohop/virtualenvs/pypy_5_10/site-packages/tblib/__init__.py", line 69, in __init__
    self.tb_frame = Frame(tb.tb_frame)
AttributeError: 'NoneType' object has no attribute 'tb_frame'
```

**Comment by ionelmc** [comment]
This is unrelated to Twisted right? It doesn't ever get to the `f = Failure()` part.

**Comment by ionelmc** [comment]
@arnimarj also, what version of tblib?

**Comment by arnimarj** [comment]
1.3.2

**Comment by ionelmc** [comment]
@arnimarj there is indeed a problem with Twisted that will be fixed. However the traceback you pasted doesn't match the code in the 1.3.2 release: https://github.com/ionelmc/python-tblib/blob/v1.3.2/src/tblib/__init__.py#L54

**Comment by ionelmc** [comment]
Ref: https://github.com/ionelmc/python-tblib/commit/6689724e14f4ec53516243ba3332001799a38b32

**Comment by ionelmc** [comment]
Released `v1.4.0`.
